# Generated by Django 5.1.6 on 2025-06-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.FloatField()),
                ('rate', models.FloatField(help_text='Annual Interest Rate (%)')),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
            ],
        ),
    ]
