# Generated by Django 5.1.6 on 2025-06-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdapp', '0002_fixeddeposit_customer_id_fixeddeposit_fd_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='fd_number',
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='rate',
            field=models.FloatField(help_text='Annual Interest Rate (%)'),
        ),
    ]
