# Generated by Django 5.1.6 on 2025-06-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdapp', '0003_remove_fixeddeposit_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='customer_id',
            field=models.CharField(default='TEMP123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='fd_number',
            field=models.CharField(default='TEMP123', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='rate',
            field=models.FloatField(),
        ),
    ]
