# Generated by Django 5.1.6 on 2025-06-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdapp', '0004_fixeddeposit_customer_id_fixeddeposit_fd_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='bank_name',
            field=models.CharField(default='HDFC Bank', max_length=150),
            preserve_default=False,
        ),
    ]
