# Generated by Django 5.1.6 on 2025-06-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdapp', '0005_fixeddeposit_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposit',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
