# Generated by Django 5.1.6 on 2025-06-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdapp', '0008_alter_fixeddeposit_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposit',
            name='bank_name',
            field=models.CharField(choices=[('HDFC', 'HDFC Bank'), ('SBM', 'State Bank Mauritius'), ('YES', 'Yes Bank'), ('IDFC', 'IDFC Bank'), ('ICICI', 'ICICI Bank'), ('AXIS', 'Axis Bank'), ('BOB', 'Bank of Baroda')], max_length=100),
        ),
    ]
