# Generated by Django 5.1.6 on 2025-06-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdapp', '0010_fixeddeposit_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposit',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='financial_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='principal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
