# Generated by Django 5.1.6 on 2025-06-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdapp', '0011_alter_fixeddeposit_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixeddeposit',
            name='principal',
            field=models.IntegerField(),
        ),
    ]
