# Generated by Django 5.1.6 on 2025-06-28 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdapp', '0012_alter_fixeddeposit_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='accumulation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='closing_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='interest',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='interest_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='tds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 28, 14, 11, 47, 161135, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='bank_name',
            field=models.CharField(choices=[('HDFC', 'HDFC Bank'), ('SBM', 'State Bank Mauritius'), ('YES', 'Yes Bank'), ('IDFC', 'IDFC Bank'), ('ICICI', 'ICICI Bank'), ('AXIS', 'Axis Bank'), ('BOB', 'Bank of Baroda')], max_length=100),
        ),
    ]
