# Generated by Django 5.1.6 on 2025-07-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdapp', '0013_fixeddeposit_accumulation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='financial_year',
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='accumulation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='yes', max_length=3),
            preserve_default=False,
        ),
    ]
