# Generated by Django 5.1.6 on 2025-07-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdapp', '0014_remove_fixeddeposit_financial_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='financial_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fixeddeposit',
            name='accumulation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
    ]
